const data = {
  products: [
    {
      name: 'Abaaya-Long',
      slug: 'abaaya-long-dubai',
      category: 'Dubai-Abaaya',
      image: './images/A1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Abaaya',
      rating: 3.5,
      numReviews: 10,
      description: 'High quality abaaya',
    },
    {
      name: 'Abaaya-short',
      slug: 'abaaya-short-dubai',
      category: 'Dubai-Abaaya',
      image: './images/A2.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Abaaya',
      rating: 1.5,
      numReviews: 10,
      description: 'High quality abaaya',
    },
    {
      name: 'Long-Jalabia',
      slug: 'jalabia-long-dubai',
      category: 'Dubai-jalibab',
      image: './images/j1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'jalibab',
      rating: 2.5,
      numReviews: 10,
      description: 'High quality jalibab',
    },
    {
      name: 'Short-Jalabia',
      slug: 'jalabia-short-dubai',
      category: 'Saudi-jalibab',
      image: './images/j2.jpg',
      price: 120,
      countInStock: 10,
      brand: 'jalibab',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality jalibab',
    },
  ],
};

export default data;
